server:
  port: 8083

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb+srv://xxxx:xxxx@xxxxx.mongodb.net/?retryWrites=true&w=majority
      database: microservicios
  application:
    name: QUALIFICATION-SERVICE
eureka:
#  instance:
#    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
